services:
  - type: web
    name: hh
    runtime: static
    branch: main
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
